/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/nintendo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.63}>
        <mesh
          geometry={nodes.Nbackbody.geometry}
          material={materials.Backbody}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nbody.geometry}
          material={materials.Body}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nbolt.geometry}
          material={materials.Bolt}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nborder.geometry}
          material={materials.Border}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Ndisplay.geometry}
          material={materials.Display}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nhand_left.geometry}
          material={materials.Controller_Left}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nhand_right.geometry}
          material={materials.Controller_Right}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Njoy.geometry}
          material={materials.Joystick}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Nport.geometry}
          material={materials.Port}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
        <mesh
          geometry={nodes.Ntiny.geometry}
          material={materials.Tiny}
          position={[-1.03, 0.94, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/nintendo.gltf')
